# Generated by Django 4.2.13 on 2024-05-22 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Database',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.IntegerField()),
                ('video_id', models.CharField(max_length=200)),
                ('title', models.CharField(default=' ', max_length=200)),
                ('pub_date', models.DateTimeField()),
                ('views', models.IntegerField()),
                ('duration', models.CharField(max_length=200)),
                ('miniature', models.CharField(max_length=200)),
                ('game', models.BooleanField()),
                ('game_title', models.CharField(blank=True, max_length=200, null=True)),
                ('feat', models.BooleanField()),
                ('feat_members', models.CharField(blank=True, max_length=200, null=True)),
                ('irl_face_none', models.CharField(choices=[('No cam', 'No cam'), ('Face cam', 'Face cam'), ('IRL cam', 'IRL cam')], max_length=20)),
            ],
        ),
    ]
