# Generated by Django 4.2.13 on 2024-05-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='feat_or_not',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='database',
            name='game_category',
            field=models.CharField(default=' ', max_length=200),
        ),
        migrations.AddField(
            model_name='database',
            name='irl_face_none',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='database',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
