# Generated by Django 4.2.13 on 2024-05-19 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_database_game_or_not'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
