# Generated by Django 4.2.13 on 2024-05-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_database_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='database',
            name='title',
            field=models.CharField(default=' ', max_length=200),
        ),
    ]
